Feature/scoreboard replay new riv version
prototyp3-dev/world-arcade-app pull request #14
Opened 2024-01-27 02:05 UTC by lynoferraz

2024-01-27 16:27 UTC, edubart requested changes

2024-01-27 16:27 UTC, edubart commented on frontend/app/components/Rivemu.tsx
> +                setGameplay(new Uint8Array(rivlog),decoder.decode(outcard));
Don't decode outcard, pass it as raw binary data, otherwise outcard will not match with the backend.

2024-01-27 16:27 UTC, edubart commented on frontend/app/components/Rivemu.tsx
> +            const outcard_json = JSON.parse(outcard_str.substring(4)); // .replace(/\,(?!\s*?[\{\[\"\'\w])/g, '')
You can remove the replace comment.

2024-01-27 16:27 UTC, edubart commented on app/replay.py
> +    outcard_hash = k.update(outcard_raw.replace(b'\r',b"").replace(b'\t',b"").replace(b'\n',b"").replace(b' ',b"")).digest()
You can remove the replaces, don't manipulate outcard binary data.

2024-01-27 16:27 UTC, edubart commented on app/scoreboard.py
> +    # outcard_hash = k.update(outcard_raw.replace(b'\r',b"").replace(b'\t',b"").replace(b'\n',b"").replace(b' ',b"")).digest()
You can remove the replace comment.

2024-01-27 16:27 UTC, edubart commented on frontend/app/components/CartridgeInfo.tsx
> +        const outcardhash = ethers.utils.keccak256(ethers.utils.toUtf8Bytes(selectedCartridge.outcard.replace(/\s|\n|\r|\t/g, '')));
You can remove the replace, as well UTF-8 byte treatment. Outcard is raw binary data.

2024-01-27 16:27 UTC, edubart commented on app/riv.py
You can remove all `strip()` calls from this file. Treat everything as raw binary data.

2024-01-27 16:27 UTC, edubart commented on app/riv.py
>      p2 = subprocess.Popen(["grep","-A1","==== BEGIN OUTCARD ===="],stdin=p1.stdout,stdout=subprocess.PIPE)
Don't capture outcard from stdout, use the `-save-outcard=<filename>` option, and read the output as binary data.

2024-01-27 16:27 UTC, edubart commented on frontend/app/components/Rivemu.tsx
>              const outcard_str = decoder.decode(outcard);
You can only decode as a string if the first 4 bytes is `JSON`, otherwise this is not a JSON, it may be something else (an image, a game save state, or something else).

2024-01-29 17:27 UTC, lynoferraz commented on frontend/app/components/Rivemu.tsx
> +                setGameplay(new Uint8Array(rivlog),decoder.decode(outcard));
Tis wo was here to avoid the outcard hash inconsistencies. I'll recheck everything and remove it if it does't break (the current version)

2024-01-29 17:29 UTC, lynoferraz commented on app/replay.py
> +    outcard_hash = k.update(outcard_raw.replace(b'\r',b"").replace(b'\t',b"").replace(b'\n',b"").replace(b' ',b"")).digest()
Same as the other comment

2024-01-31 11:50 UTC, lynoferraz commented on app/replay.py
> +    outcard_hash = k.update(outcard_raw.replace(b'\r',b"").replace(b'\t',b"").replace(b'\n',b"").replace(b' ',b"")).digest()
Used the outhash from riv

2024-01-31 11:51 UTC, lynoferraz commented on app/riv.py
>      p2 = subprocess.Popen(["grep","-A1","==== BEGIN OUTCARD ===="],stdin=p1.stdout,stdout=subprocess.PIPE)
Used the outhash from riv

2024-01-31 11:52 UTC, lynoferraz commented on frontend/app/components/Rivemu.tsx
> +                setGameplay(new Uint8Array(rivlog),decoder.decode(outcard));
Used the outhash from riv

2024-01-31 15:34 UTC, arthuravianna commented on frontend/app/components/CartridgeScoreboard.tsx
>                                  <td scope="row" className="px-6 py-4 break-all">
Since the address is being truncated, adding the "title" property will create a hover effect that displays the complete address. It will also be useful if we have nicknames or things like that.
```suggestion
                                <td scope="row" title={scoreInfo.user_address} className="px-6 py-4 break-all">
```

2024-01-31 15:41 UTC, arthuravianna commented on frontend/app/components/CartridgeScoreboard.tsx
> +function CartridgeScoreboard({cartridge_id, replay_function}:{cartridge_id:string,replay_function(replayScore: ReplayScore): void}) {
@lynoferraz, the Suspense fallback effect only works with async components. This guy should remain async and the Suspense should be around it to create that "loading" effect.

2024-01-31 15:42 UTC, arthuravianna commented on frontend/app/components/CartridgeInfo.tsx
> -                                <Suspense fallback={scoreboardFallback()}>
Is there any particular reason for removing the Suspense here?

2024-01-31 15:58 UTC, edubart commented on app/cartridge.py
> +    if outcard_raw is None or len(outcard_raw) == 0:
Outcard can have 0 length, in case of cartridges that are just artwork.

2024-01-31 17:13 UTC, arthuravianna reviewed
The features introduced are working. However, the fallback animation for the scoreboard is not working anymore.

2024-01-31 19:50 UTC, lynoferraz commented on app/cartridge.py
> +    if outcard_raw is None or len(outcard_raw) == 0:
Ok. I'll remove this test. So it will only test if it can start the cartridge

2024-01-31 19:53 UTC, lynoferraz commented on frontend/app/components/CartridgeScoreboard.tsx
> +function CartridgeScoreboard({cartridge_id, replay_function}:{cartridge_id:string,replay_function(replayScore: ReplayScore): void}) {
This was moved to inside the component. So the component has the suspense effect

2024-01-31 19:53 UTC, lynoferraz commented on frontend/app/components/CartridgeInfo.tsx
> -                                <Suspense fallback={scoreboardFallback()}>
Th e suspense effect was moved to inside the component.

2024-02-01 20:38 UTC, felipefg approved these changes
LGFM

2024-02-01 20:38 UTC, merged