Feature/dynamic screenshot text riv v0.2.2 alpha
prototyp3-dev/world-arcade-app pull request #18
Opened 2024-02-21 17:16 UTC by lynoferraz

2024-02-22 20:37 UTC, arthuravianna requested changes

2024-02-22 20:37 UTC, arthuravianna commented on frontend/app/mint/[input_index]/page.tsx
> +export function byteToBase64(bytes: Uint8Array): String {
This export makes the build fail.
```suggestion
function byteToBase64(bytes: Uint8Array): String {
```

2024-02-22 20:37 UTC, arthuravianna commented on frontend/app/mint/[input_index]/page.tsx
> +      registerMessage = <span>(operator can't register)</span>;
Must use the escaped apostrophe, otherwise the build also fails.
```suggestion
      registerMessage = <span>(operator can&apos;t register)</span>;
```

2024-02-24 20:41 UTC, felipefg approved these changes
lgtm

2024-02-24 20:41 UTC, merged